language: java
branches:
  only:
    - milestone-3

jdk:
  - oraclejdk8
sudo: required

services:
  - docker


install:
  - cd "SG_MICROSERVICE_STORMDETECTOR" && mvn -e clean install
  - docker build -t kedargn/stormdetector ../.
  - docker ps -a
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push kedargn/stormdetector

script: mvn clean install -DskipTests=true

after_success:
  - cd ..

before_deploy:
  - zip -r SG_MICROSERVICE_STORMDETECTOR.zip scripts appspec.yml || true
  - mkdir -p "dpl_java_upload"
  - mv SG_MICROSERVICE_STORMDETECTOR.zip dpl_java_upload/SG_MICROSERVICE_STORMDETECTOR.zip || true

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: sga-teamnpcomplete
    local_dir: dpl_java_upload
    region: us-west-2
    skip_cleanup: true
    acl: public_read
    detect_encoding: true
    on:
      branch: milestone-3


  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: sga-teamnpcomplete
    key: SG_MICROSERVICE_STORMDETECTOR.zip
    bundle_type: zip
    application: TeamNPComplete
    deployment_group: TeamNPComplete
    region: us-west-2
    on:
      branch: milestone-3

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY_TEST # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY_TEST
    bucket: sga-teamnpcomplete
    key: SG_MICROSERVICE_STORMDETECTOR.zip
    bundle_type: zip
    application: TeamNPCompleteTest
    deployment_group: TeamNPCompleteTest
    region: us-west-2
    on:
      branch: milestone-3

  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings.
    secret_access_key: $AWS_SECRET_KEY
    bucket: sga-npcomplete-east
    local_dir: dpl_java_upload
    region: us-east-2
    skip_cleanup: true
    acl: public_read
    detect_encoding: true
    on:
      branch: milestone-3

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: sga-npcomplete-east
    key: SG_MICROSERVICE_STORMDETECTOR.zip
    bundle_type: zip
    application: TeamNpComplete3
    deployment_group: TeamNpComplete3
    region: us-east-2
    on:
      branch: milestone-3
